apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mikes-system-test-mikes-quarkus-server-qa
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    system: mikes-system-test
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-mal/developer-charts
    targetRevision: HEAD
    path: quarkus-application
    helm:
      values: |
        system: mikes-system-test
        component: mikes-quarkus-server
        environment: qa
        image:
          tag: latest
        replicaCount: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: mikes-system-test-qa
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
