apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-test-consume-prod
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-mal/developer-charts
    targetRevision: HEAD
    path: spring-boot-application
    helm:
      values: |
        system: mikes-system-test
        component: spring-test-consume
        environment: prod
        image:
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: mikes-system-test-prod
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m